/**
 * Generated by scripts/gen-api-types.ts from src/api/schema.json, which
 * scripts/gen_api_schema.py writes from tape.api.contract. Do not edit: change the
 * msgspec structs, then run `uv run python scripts/gen_api_schema.py` and
 * `npm run api-types`. The app reads these types through protocol.ts.
 */

/**
 * Every REST response body and live feed message of tape serve (docs/FRONTEND.md 4). Generated from tape.api.contract by scripts/gen_api_schema.py; do not edit.
 */
export type TapeLiveAPI =
  MarketsResponse | MarketDetail | ServiceStatus | ErrorResponse | ServerMessage | SubscribeRequest;
export type ServerMessage =
  | HelloMessage
  | SubscribedMessage
  | SnapshotMessage
  | DeltaMessage
  | BookMessage
  | ResyncMessage
  | TradeMessage
  | TickerMessage
  | ErrorMessage;

/**
 * ``GET /markets``: recorded markets by 24-hour volume, highest first, then by ticker.
 *
 * Attributes:
 *     markets: At most ``limit`` rows.
 */
export interface MarketsResponse {
  markets: MarketRow[];
}
/**
 * One recorded market, as ``GET /markets`` lists it.
 *
 * Attributes:
 *     ticker: Market ticker.
 *     event_ticker: Event the market belongs to.
 *     series_ticker: Series the market belongs to.
 *     title: The event's title, or ``null`` until resolved.
 *     subtitle: The market's YES subtitle, or ``null`` until resolved.
 *     category: The series category, or ``null`` until resolved.
 *     showcase: Whether a series group admitted the market to the recorded universe (ADR 0028).
 *     volume_24h_e2: Contracts traded in the 24 hours before the recorder's latest listing.
 *     close_ts: Unix seconds at which the market closes, or ``null`` when unknown.
 *     bid_e4: Best YES bid from the latest ticker update, or ``null``.
 *     ask_e4: Best YES ask from the latest ticker update, or ``null``.
 *     last_e4: Last trade price from the latest ticker update, or ``null``.
 *     book: How far the server's copy of the book can be trusted.
 */
export interface MarketRow {
  ask_e4: number | null;
  bid_e4: number | null;
  book: "fresh" | "stale" | "unknown";
  category: string | null;
  close_ts: number | null;
  event_ticker: string;
  last_e4: number | null;
  series_ticker: string;
  showcase: boolean;
  subtitle: string | null;
  ticker: string;
  title: string | null;
  volume_24h_e2: number;
}
/**
 * One recorded market with its price grid and depth, from ``GET /markets/{ticker}``.
 *
 * Attributes:
 *     price_ranges: The market's price grid, or ``null`` until resolved.
 *     depth: The best levels per side, or ``null`` unless the book is known.
 */
export interface MarketDetail {
  ask_e4: number | null;
  bid_e4: number | null;
  book: "fresh" | "stale" | "unknown";
  category: string | null;
  close_ts: number | null;
  depth: null | Depth;
  event_ticker: string;
  last_e4: number | null;
  price_ranges: PriceRange[] | null;
  series_ticker: string;
  showcase: boolean;
  subtitle: string | null;
  ticker: string;
  title: string | null;
  volume_24h_e2: number;
}
/**
 * The top of a book the server holds.
 *
 * Attributes:
 *     ts_ms: Exchange time of the last change applied to the book, or ``null`` when unknown.
 *     bids: Up to :data:`DEPTH_LEVELS` YES bids, highest first.
 *     asks: Up to :data:`DEPTH_LEVELS` YES asks, lowest first.
 */
export interface Depth {
  asks: [number, number][];
  bids: [number, number][];
  ts_ms: number | null;
}
/**
 * One band of a market's price grid.
 *
 * Attributes:
 *     start_e4: Lowest price of the band.
 *     end_e4: Highest price of the band.
 *     step_e4: Tick size within the band.
 */
export interface PriceRange {
  end_e4: number;
  start_e4: number;
  step_e4: number;
}
/**
 * ``GET /status``.
 *
 * Attributes:
 *     recording: Whether a recorder status report arrived within two of its intervals.
 *     recorder_status_age_ms: Milliseconds since that report arrived, or ``null`` before any.
 *     recorder: The latest report, or ``null`` before any.
 *     bus: The server's view of the bus.
 *     clients: Open live connections.
 */
export interface ServiceStatus {
  bus: BusHealth;
  clients: number;
  recorder: null | RecorderHealth;
  recorder_status_age_ms: number | null;
  recording: boolean;
}
/**
 * How the server follows the recorder's bus.
 *
 * Attributes:
 *     epoch: The recorder run the latest message came from, or ``null`` before any: its
 *         ``bus_epoch``, a wall-clock nanosecond count, as a decimal string. It identifies a run
 *         and exceeds what a JavaScript number holds exactly, so clients only compare it.
 *     last_seq: Number of the latest message, or ``null`` before any.
 *     messages: Messages received.
 *     resets: Times every book was dropped: at the first message, a recorder restart, or loss.
 *     missed: Messages known to be lost.
 *     books_known: Books the server holds now.
 */
export interface BusHealth {
  books_known: number;
  epoch: string | null;
  last_seq: number | null;
  messages: number;
  missed: number;
  resets: number;
}
/**
 * The recorder's latest status report.
 *
 * Attributes:
 *     universe_size: Markets the recorder chose to record.
 *     subscribed_markets: Markets whose order-book subscriptions are live.
 *     connections: Every connection, by ascending id.
 */
export interface RecorderHealth {
  connections: ConnectionHealth[];
  subscribed_markets: number;
  universe_size: number;
}
/**
 * One recorder connection's counters.
 *
 * Attributes:
 *     conn_id: Connection id.
 *     taped: Whether the connection writes to the tape.
 *     frames: Frames received since the recorder started.
 *     gaps: Sequence gaps observed since start.
 *     reconnects: Reconnections since start.
 *     stale_books: Books awaiting a snapshot now.
 *     sink_dropped: Records that never reached the tape.
 */
export interface ConnectionHealth {
  conn_id: number;
  frames: number;
  gaps: number;
  reconnects: number;
  sink_dropped: number;
  stale_books: number;
  taped: boolean;
}
/**
 * The body of every REST error.
 *
 * Attributes:
 *     error: The error.
 */
export interface ErrorResponse {
  error: ErrorBody;
}
/**
 * What went wrong.
 *
 * Attributes:
 *     code: A stable, machine-readable code such as ``unknown_ticker``.
 *     message: A human-readable explanation.
 */
export interface ErrorBody {
  code: string;
  message: string;
}
/**
 * The first message on every connection.
 *
 * Attributes:
 *     protocol: :data:`PROTOCOL_VERSION`.
 *     max_tickers: Most markets one subscription may name.
 *     bus_refresh_s: Longest wait for a snapshot after ``resync`` with ``bus_loss``.
 */
export interface HelloMessage {
  bus_refresh_s: number;
  max_tickers: number;
  protocol: number;
  t: "hello";
}
/**
 * The reply to each ``subscribe``.
 *
 * Attributes:
 *     tickers: The new subscription set, in the order the client named the markets.
 *     rejected: The tickers left out, and why.
 */
export interface SubscribedMessage {
  rejected: Rejection[];
  t: "subscribed";
  tickers: string[];
}
/**
 * A ticker a subscription could not include.
 *
 * Attributes:
 *     ticker: The ticker as the client sent it.
 *     code: ``unknown_ticker`` when the market is not recorded, ``too_many_tickers`` beyond
 *         ``max_tickers``.
 */
export interface Rejection {
  code: "too_many_tickers" | "unknown_ticker";
  ticker: string;
}
/**
 * A market's whole book, replacing whatever the client holds.
 *
 * Attributes:
 *     ticker: Market ticker.
 *     book: Whether the book is fresh or stale.
 *     ts_ms: Exchange time of the last change applied to the book, or ``null`` when unknown.
 *     bids: Every YES bid, highest first.
 *     asks: Every YES ask, lowest first.
 */
export interface SnapshotMessage {
  asks: [number, number][];
  bids: [number, number][];
  book: "fresh" | "stale";
  t: "snapshot";
  ticker: string;
  ts_ms: number | null;
}
/**
 * A signed change at one level, applied to the latest snapshot.
 *
 * Attributes:
 *     ticker: Market ticker.
 *     ts_ms: Exchange time of the change, or ``null`` when unknown.
 *     side: The side of the level.
 *     price_e4: The level's price.
 *     delta_e2: Signed change in the level's resting count; the level is removed at zero.
 */
export interface DeltaMessage {
  delta_e2: number;
  price_e4: number;
  side: "ask" | "bid";
  t: "delta";
  ticker: string;
  ts_ms: number | null;
}
/**
 * A book's freshness changed without a snapshot.
 *
 * Attributes:
 *     ticker: Market ticker.
 *     book: The new state; a stale book receives no deltas until its next snapshot.
 */
export interface BookMessage {
  book: "fresh" | "stale";
  t: "book";
  ticker: string;
}
/**
 * Discard this market's book; a snapshot follows once the server's book is known.
 *
 * Attributes:
 *     ticker: Market ticker.
 *     reason: ``client_lag`` when this connection fell behind, and the snapshot follows at
 *         once; ``bus_loss`` when the server lost its book, and the snapshot follows within
 *         ``bus_refresh_s``.
 */
export interface ResyncMessage {
  reason: "bus_loss" | "client_lag";
  t: "resync";
  ticker: string;
}
/**
 * A public trade.
 *
 * Attributes:
 *     ticker: Market ticker.
 *     ts_ms: Exchange time of the trade.
 *     price_e4: YES price of the trade.
 *     count_e2: Contracts traded.
 *     taker_side: ``bid`` when the taker bought YES.
 */
export interface TradeMessage {
  count_e2: number;
  price_e4: number;
  t: "trade";
  taker_side: "ask" | "bid";
  ticker: string;
  ts_ms: number;
}
/**
 * Top of book and cumulative volume.
 *
 * Attributes:
 *     ticker: Market ticker.
 *     ts_ms: Exchange time of the update.
 *     bid_e4: Best YES bid, or ``null``.
 *     ask_e4: Best YES ask, or ``null``.
 *     last_e4: Last trade price, or ``null``.
 *     volume_e2: Contracts traded since the market opened.
 */
export interface TickerMessage {
  ask_e4: number | null;
  bid_e4: number | null;
  last_e4: number | null;
  t: "ticker";
  ticker: string;
  ts_ms: number;
  volume_e2: number;
}
/**
 * A client message the server could not accept; the connection stays open.
 *
 * Attributes:
 *     code: ``malformed_json``, ``unknown_op``, or ``invalid_message``.
 *     message: A human-readable explanation.
 */
export interface ErrorMessage {
  code: string;
  message: string;
  t: "error";
}
/**
 * Replace the subscription set; an empty list unsubscribes from everything.
 *
 * Attributes:
 *     tickers: The markets to follow.
 */
export interface SubscribeRequest {
  op: "subscribe";
  tickers: string[];
}
