/**
 * Writes `src/api/schema.gen.ts`, the TypeScript types of every live API message, from
 * `src/api/schema.json` (ADR 0023, docs/ENGINEERING_STANDARDS.md section 6).
 *
 *   npm run api-types          # write the file
 *   npm run api-types:check    # write nothing; exit 1 when the committed file is stale
 *
 * The msgspec structs in `tape.api.contract` are the source of truth:
 * `scripts/gen_api_schema.py` writes the schema from them, and this script only translates
 * it. The output is deterministic: the schema's order, a fixed banner, and the repository's
 * Prettier configuration, so `prettier --check` accepts it unchanged.
 */

import { readFile, writeFile } from "node:fs/promises";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { compile } from "json-schema-to-typescript";
import { format, resolveConfig } from "prettier";

type Schema = Parameters<typeof compile>[0];

const WEB_ROOT = fileURLToPath(new URL("..", import.meta.url));
const SCHEMA_PATH = fileURLToPath(new URL("../src/api/schema.json", import.meta.url));
const OUTPUT_PATH = fileURLToPath(new URL("../src/api/schema.gen.ts", import.meta.url));

const BANNER = `/**
 * Generated by scripts/gen-api-types.ts from src/api/schema.json, which
 * scripts/gen_api_schema.py writes from tape.api.contract. Do not edit: change the
 * msgspec structs, then run \`uv run python scripts/gen_api_schema.py\` and
 * \`npm run api-types\`. The app reads these types through protocol.ts.
 */`;

/**
 * Rewrites JSON Schema 2020-12 tuples (`prefixItems` with `items: false`), which msgspec
 * emits for Python tuples such as a `[price_e4, count_e2]` level, into the draft-07 form
 * (`items` as an array, `additionalItems: false`) that json-schema-to-typescript turns
 * into TypeScript tuples. Everything else is copied unchanged.
 */
function withDraft7Tuples(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(withDraft7Tuples);
  if (typeof node !== "object" || node === null) return node;
  const entries = Object.entries(node as Record<string, unknown>);
  const copy = Object.fromEntries(entries.map(([key, value]) => [key, withDraft7Tuples(value)]));
  if (!("prefixItems" in copy)) return copy;
  const { prefixItems, items, ...rest } = copy;
  if (items !== false) throw new Error("only closed tuples (items: false) are supported");
  return { ...rest, items: prefixItems, additionalItems: false };
}

async function render(): Promise<string> {
  const parsed: unknown = JSON.parse(await readFile(SCHEMA_PATH, "utf8"));
  const schema = withDraft7Tuples(parsed) as Schema;
  const code = await compile(schema, "TapeLiveApi", {
    additionalProperties: false,
    bannerComment: BANNER,
    format: false,
    unknownAny: true,
  });
  const style = await resolveConfig(OUTPUT_PATH);
  return format(code, { ...style, filepath: OUTPUT_PATH });
}

async function main(): Promise<number> {
  const { values } = parseArgs({ options: { check: { type: "boolean", default: false } } });
  const expected = await render();
  const shown = relative(WEB_ROOT, OUTPUT_PATH);
  if (values.check) {
    const current = await readFile(OUTPUT_PATH, "utf8").catch(() => "");
    if (current !== expected) {
      process.stderr.write(`${shown} is stale; run: npm run api-types\n`);
      return 1;
    }
    process.stdout.write(`${shown} is current\n`);
    return 0;
  }
  await writeFile(OUTPUT_PATH, expected);
  process.stdout.write(`wrote ${shown}\n`);
  return 0;
}

process.exitCode = await main();
