"""The recorder's pure decisions: what to capture, how to subscribe, and where data has holes.

``universe`` chooses the markets that earn full order-book capture, ``planner`` assigns
them to order-book connections and turns plan changes into WebSocket commands (ADR 0020),
and ``gaps`` detects sequence discontinuities per subscription (docs/INTERFACES.md 8).
"""

from tape.recorder.gaps import Duplicate, FirstMessage, Gap, GapTracker, GapVerdict, Ok
from tape.recorder.planner import (
    AddGroup,
    AddMarkets,
    Group,
    Plan,
    PlanChange,
    RemoveGroup,
    RemoveMarkets,
    diff,
    group_sort_key,
    plan,
    split_change,
    to_commands,
)
from tape.recorder.universe import (
    ACTIVE_STATUS,
    DEFAULT_EXCHANGE_INDEX,
    MARKET_ORDER_NEAR_PRICE,
    MARKET_ORDER_VOLUME,
    MARKET_ORDERS,
    RANGE_STRIKE_TYPE,
    REASON_BELOW_VOLUME,
    REASON_BEYOND_HORIZON,
    REASON_CLOSED,
    REASON_DUPLICATE,
    REASON_EVENT_BEYOND_HORIZON,
    REASON_EVENT_NOT_CHOSEN,
    REASON_MVE,
    REASON_NO_GROUP,
    REASON_NOT_ACTIVE,
    REASON_OVER_CAP,
    REASON_OVER_EVENT_CAP,
    REASON_OVER_GROUP_CAP,
    REASONS,
    THRESHOLD_STRIKE_TYPES,
    GroupSelection,
    MarketOrder,
    MarketSummary,
    UniverseDecision,
    UniverseGroup,
    UniversePolicy,
    select,
    series_of,
    yes_mid,
)

__all__ = [
    "ACTIVE_STATUS",
    "DEFAULT_EXCHANGE_INDEX",
    "MARKET_ORDERS",
    "MARKET_ORDER_NEAR_PRICE",
    "MARKET_ORDER_VOLUME",
    "RANGE_STRIKE_TYPE",
    "REASONS",
    "REASON_BELOW_VOLUME",
    "REASON_BEYOND_HORIZON",
    "REASON_CLOSED",
    "REASON_DUPLICATE",
    "REASON_EVENT_BEYOND_HORIZON",
    "REASON_EVENT_NOT_CHOSEN",
    "REASON_MVE",
    "REASON_NOT_ACTIVE",
    "REASON_NO_GROUP",
    "REASON_OVER_CAP",
    "REASON_OVER_EVENT_CAP",
    "REASON_OVER_GROUP_CAP",
    "THRESHOLD_STRIKE_TYPES",
    "AddGroup",
    "AddMarkets",
    "Duplicate",
    "FirstMessage",
    "Gap",
    "GapTracker",
    "GapVerdict",
    "Group",
    "GroupSelection",
    "MarketOrder",
    "MarketSummary",
    "Ok",
    "Plan",
    "PlanChange",
    "RemoveGroup",
    "RemoveMarkets",
    "UniverseDecision",
    "UniverseGroup",
    "UniversePolicy",
    "diff",
    "group_sort_key",
    "plan",
    "select",
    "series_of",
    "split_change",
    "to_commands",
    "yes_mid",
]
